const products = [
  {
    id: 1,
    name: "Americano Coffee Beans",
    image: "/images/Americano.png",
    brand: "Grounds & Co.",
    price: 25,
    rating: 3,
    numReviews: 10,
    countInStock: 4,
  },
  {
    id: 2,
    name: "Arabica Coffee Beans",
    image: "/images/Arabica.png",
    brand: "Grounds & Co.",
    price: 25.0,
    rating: 3.8,
    numReviews: 8,
    countInStock: 4,
  },
  {
    id: 3,
    name: "Breakfast Blend Coffee Beans",
    image: "/images/Breakfast.png",
    brand: "Grounds & Co.",
    price: 25.0,
    rating: 3.5,
    numReviews: 14,
    countInStock: 4,
  },
  {
    id: 4,
    name: "Colombian Coffee Beans",
    image: "/images/Colombian.png",
    brand: "Grounds & Co.",
    price: 25.0,
    rating: 3,
    numReviews: 34,
    countInStock: 4,
  },
  {
    id: 5,
    name: "Espresso Coffee Beans",
    image: "/images/Espresso.png",
    brand: "Grounds & Co.",
    price: 25.0,
    rating: 4,
    numReviews: 10,
    countInStock: 4,
  },
  {
    id: 6,
    name: "Excelsa Coffee Beans",
    image: "/images/Excelsa.png",
    brand: "Grounds & Co.",
    price: 25.0,
    rating: 3.5,
    numReviews: 23,
    countInStock: 4,
  },
  {
    id: 7,
    name: "Geisha Coffee Beans",
    image: "/images/Geisha.png",
    brand: "Grounds & Co.",
    price: 25,
    rating: 5,
    numReviews: 11,
    countInStock: 4,
  },
  {
    id: 8,
    name: "Liberica Coffee Beans",
    image: "/images/Liberica.png",
    brand: "Grounds & Co.",
    price: 25,
    rating: 3.5,
    numReviews: 5,
    countInStock: 4,
  },
  {
    id: 9,
    name: "Robusta Coffee Beans",
    image: "/images/Robusta.png",
    brand: "Grounds & Co.",
    price: 25,
    rating: 3,
    numReviews: 10,
    countInStock: 4,
  },
  {
    id: 23,
    name: "Original Coffee Beans",
    image: "/images/Original.png",
    brand: "Grounds & Co.",
    price: 25,
    rating: 3.5,
    numReviews: 10,
    countInStock: 4,
  },
  {
    id: 10,
    name: "Drip Coffee Maker",
    category: "Coffee Makers",
    image: "/images/DripCoffeeMaker.png",
    brand: "Grounds & Co.",
    price: 45,
    rating: 4,
    numReviews: 23,
    countInStock: 4,
  },
  {
    id: 11,
    name: "French Press",
    image: "/images/FrenchPressMaker.png",
    brand: "Grounds & Co.",
    price: 20,
    rating: 4,
    numReviews: 43,
    countInStock: 4,
  },
  {
    id: 12,
    name: "Espresso Machine",
    image: "/images/EspressoMachine.png",
    brand: "Grounds & Co.",
    price: 80,
    rating: 4.5,
    numReviews: 342,
    countInStock: 4,
  },
  {
    id: 13,
    name: "Pour Over Coffee Maker",
    image: "/images/PourOverNew.png",
    brand: "Grounds & Co.",
    price: 15,
    rating: 4,
    numReviews: 13,
    countInStock: 4,
  },
  {
    id: 14,
    name: "Green Mug",
    image: "/images/GreenCup.png",
    brand: "Grounds & Co.",
    price: 3,
    rating: 3.5,
    numReviews: 34,
    countInStock: 4,
  },
  {
    id: 15,
    name: "Blue Mug",
    image: "/images/skyblue.png",
    brand: "Grounds & Co.",
    price: 4,
    rating: 5,
    numReviews: 34,
    countInStock: 4,
  },
  {
    id: 16,
    name: "White Mug",
    image: "/images/WhiteCup.png",
    brand: "Grounds & Co.",
    price: 2,
    rating: 4,
    numReviews: 43,
    countInStock: 4,
  },
  {
    id: 17,
    name: "Dark Blue Mug",
    image: "/images/DarkBlueCup.png",
    brand: "Grounds & Co.",
    price: 4,
    rating: 4,
    numReviews: 13,
    countInStock: 4,
  },
  {
    id: 18,
    name: "Black Large Thermo",
    image: "/images/BlackLargeThermo.png",
    brand: "Grounds & Co.",
    price: 12,
    rating: 5,
    numReviews: 103,
    countInStock: 4,
  },
  {
    id: 19,
    name: "Red Mug",
    image: "/images/RedCup.png",
    brand: "Grounds & Co.",
    price: 4,
    rating: 3,
    numReviews: 23,
    countInStock: 4,
  },
  {
    id: 20,
    name: "Red Thermo",
    image: "/images/RedThermos.png",
    brand: "Grounds & Co.",
    price: 8,
    rating: 4,
    numReviews: 23,
    countInStock: 4,
  },
  {
    id: 21,
    name: "Steel Large Thermo",
    image: "/images/SteelLargeThermo.png",
    brand: "Grounds & Co.",
    price: 13,
    rating: 4.5,
    numReviews: 54,
    countInStock: 4,
  },
  {
    id: 22,
    name: "Blue Small Thermo",
    image: "/images/BlueSmThermo.png",
    brand: "Grounds & Co.",
    price: 9,
    rating: 4,
    numReviews: 15,
    countInStock: 4,
  },
];
